todo_project/accounts/urls.py
from django.urls import path, include
from . import views

app_name='accounts'

urlpatterns = [
    path('', views.account_login, name='login'),
    path('signup/', views.account_signup, name='signup'),
    path('logout/', views.account_logout, name='logout'),
]

todo_project/articles/urls.py
from django.urls import path, include
from . import views

app_name='articles'

urlpatterns = [
    path('', views.article_homepage, name='list'),
    path('<id>', views.article_detail, name='detail'),
    path('owner/<id>', views.article_detail_own, name='detailowned'),
    path('create/', views.article_create, name='create'),
    path('my-article/', views.article_owned, name='owned'),
    path('create/<int:id>/', views.article_create, name='create'),
    path('delete/<int:id>/', views.article_delete, name='delete'),
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from accounts import views as account_views

urlpatterns = [
    path('admin/jme/', admin.site.urls),
    path('', account_views.account_login),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_project/accounts/models.py
from django.db import models

# Create your models here.

todo_project/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    thumbnail = models.ImageField(default='default.png', blank=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.title.upper()

    def capital(self):
        auth_cap = str(self.author)
        return auth_cap.capitalize()
    
    def snippets(self):
        
        return self.body[:30].capitalize() + '...'

todo_project/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body','thumbnail']

        widgets = {
            'title' : forms.TextInput(attrs={
                "placeholder":"Enter Title",
                "minlength":"4",
            }),
            'body' : forms.Textarea(attrs={
                "data-rule":"required",
                "minlength":"2",
                "data-msg":"Please write something for me",
                "placeholder": "Message"
            })
        }

todo_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse

def account_login(request):
    if request.method == 'GET':
        form = AuthenticationForm()
        return render(request, 'accounts/accounts_index.html', {'form': form, 'active4':'active'})
    elif request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
        else:
            err_msg = "Username and Password did not matched"
        return render(request, 'accounts/accounts_index.html', {'form': form, 'active4':'active', 'errmsg':err_msg})

def account_signup(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'accounts/accounts_signup.html', {'form': form, 'active5':'active'})
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
        return render(request, 'accounts/accounts_signup.html', {'form': form, 'active5':'active'})

def account_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

todo_project/articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

@login_required(login_url='accounts:login')
def article_homepage(request):
    if request.method == 'GET':
        articles = models.Article.objects.all().order_by('-date')
        article_count = models.Article.objects.all().count()
        return render(request, 'articles/articles_index.html', {'articles': articles, 'count':article_count,'active2':'active'})


@login_required(login_url='accounts:login')
def article_owned(request):
    if request.method == 'GET':
        articles = models.Article.objects.all().filter(author=request.user.id).order_by('-date')
        article_count = models.Article.objects.all().filter(author=request.user.id).count()
        return render(request, 'articles/articles_my_article.html', {'articles': articles, 'count':article_count, 'active3':'active'})


@login_required(login_url='accounts:login')
def article_detail(request, id=0):
    article = models.Article.objects.get(id=id)
    if request.method == 'GET':
        return render(request, 'articles/articles_detail.html', {'article':article })


@login_required(login_url='accounts:login')
def article_detail_own(request, id=0):
    article = models.Article.objects.get(id=id)
    if request.method == 'GET':
        if request.user == article.author:
            return render(request, 'articles/articles_detail_owner.html', {'article':article, 'active3':'active'})
        else:
            return HttpResponse('Bad Request')



@login_required(login_url='accounts:login')
def article_create(request, id=0):
    if id==0:        
        if request.method == 'GET':
            form = forms.CreateArticle()
            return render(request, 'articles/articles_create.html', {'forms': form, 'active1':'active', 'btnName':'Create'})
        elif request.method == 'POST':
            form = forms.CreateArticle(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect('articles:list')
    elif id > 0:
        article = models.Article.objects.get(id=id)
        if request.method == 'GET':
            form = forms.CreateArticle(instance=article)
            return render(request, 'articles/articles_create.html', {'forms': form, 'active1':'active', 'btnName':'Update'})
        elif request.method == 'POST':
            form = forms.CreateArticle(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:owned')



@login_required(login_url='accounts:login')
def article_delete(request, id):
    try:
        article = models.Article.objects.get(id=id)
        art_count = models.Article.objects.all().filter(id=id).count()
        if request.method == 'POST':
            article.delete()
            return redirect('articles:owned')
    except Exception as e:
        return redirect('articles:owned')

todo_project/accounts/templates/accounts/accounts_index.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block title %}
    My Todo App
{% endblock%}
{% block content %}
    <div class="col-sm-6 offset-sm-3 modified-forms-accounts">
        <p class="lead">Login</p>
        <div class="error-box">
            <p class="text-center">{{ errmsg }}</p>
        </div>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}
            {{ form.username | as_crispy_field }}
            {{ form.password | as_crispy_field }}
            <div class="col-sm-3 offset-sm-9">
                <div class="row">
                    <button type="submit" class="btn btn-success btn-block">Login</button>
                </div>
            </div>
            {% if request.GET.next %}
                <input type="hidden" name='next' value='{{ request.GET.next }}'>
            {% endif %}
        </form>
    </div>

    <script>
        $('document').ready(function(){
            $('#id_username').attr('autocomplete','off')

            {% if user.is_authenticated %}
                window.location.href = "{%url 'articles:list'%}"
            {% endif %}
        })
    </script>
    <style>

        input, #id_username, #id_password{
            background-color:rgba(19, 18, 18, 0.521);
            border:none;
            color:white;
        }
        .modified-forms-accounts{
            border:1px solid rgba(19, 18, 18, 0.164);
            padding:30px 30px;
            margin-top:10%;
            border-radius:10px;
            background-color:rgba(24, 23, 23, 0.425);
        }
        label, .lead{
            color:white;
        }

        .error-box p{
            color:rgb(236, 152, 152);
            font-weight:bold;
        }

        .btn-success{
            background-color:rgba(86, 207, 116, 0.425);
            border:none !important;
        }
    </style>
{% endblock %}

todo_project/accounts/templates/accounts/accounts_signup.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock%}
{% block content %}
    <form action="" method="POST">

        {% csrf_token %}
        <div class="col-sm-6 offset-sm-3 modified-forms-accounts">
            <p class="lead">Register</p>
            <hr>
            {{form.username | as_crispy_field}}
            {{form.password1 | as_crispy_field}}
            {{form.password2 | as_crispy_field}}
        
            <div class="row">
                <div class="col-sm-6 offset-sm-6">
                    <button type="submit" class="btn btn-success btn-block">Register</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 offset-sm-6">
                    <button type="button" id='cancelBtn' class="btn btn-danger btn-block">Cancel</button>
                </div>
            </div>
        </div>
    </form>
    <script>
        $('document').ready(function(){

            $('#id_username').attr('autocomplete','off');

            $('#cancelBtn').on('click', function(){
                window.location.href = "{% url 'accounts:login' %}";
            })

            {% if user.is_authenticated %}
                window.location.href = "{%url 'articles:list'%}"
            {% endif %}
        })


        <script>
        $('document').ready(function(){
            
        })
    </script>
    </script>
    <style>

        .lead{
            color:white;
        }
        .modified-forms-accounts{
            border:1px solid rgba(19, 18, 18, 0.164);
            padding:30px 30px;
            margin-top:10%;
            border-radius:10px;
            background-color:rgba(24, 23, 23, 0.425);
        }
        label{
            color:white;
        }

        .btn-success{
            background-color:rgba(86, 207, 116, 0.425);
            border:none !important;
        }

        .btn-danger{
            background-color:rgba(212, 73, 73, 0.479);
            border:none;
        }

        .btn{
            margin-bottom:10px;
        }

        input, #id_username, #id_password1, #id_password2{
            background-color:rgba(19, 18, 18, 0.521);
            border:none;
            color:white;
        }

    </style>
{% endblock %}

todo_project/articles/templates/articles/articles_create.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    Create Article
{% endblock%}
{% block content %}
    <div class="col-sm-6 offset-sm-3 modified-forms">
        <form action="" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {{ forms.title | as_crispy_field }}
            {{ forms.body | as_crispy_field }}
            {{ forms.thumbnail | as_crispy_field }}
            <div class="row">
                <div class="col-md-4 offset-md-4">    
                    <button type="submit" id='btnCreate' class="btn btn-success btn-block">{{btnName}}</button>
                </div>
                <div class="col-md-4">
                    <a href="{% url 'articles:list'%}" class="btn btn-block btn-danger">Back</a>
                </div>
            </div>
        </form>

    </div>

    <style>

        .btn-success{
            background-color:rgba(86, 207, 116, 0.425);
            border:none !important;
        }

        .btn-danger{
            background-color:rgba(212, 73, 73, 0.479);
            border:none;
        }
        .modified-forms{
            border:1px solid rgb(46, 44, 44);
            padding:30px 30px;
            border-radius:10px;
            background-color:rgba(34, 33, 33, 0.514);
            margin-top:100px;
        }

        input, #id_body, #id_title{
            background-color:rgba(19, 18, 18, 0.521);
            border:none;
            color:white;
        }

        label{
            color:white;
        }

        .btn{
            margin-bottom:10px !important;
        }
    </style>

    <script>

        $('#id_title').attr('autocomplete','off')


        $('document').ready(function(){
            $('form').on('submit', function(){
                $('#btnCreate').attr('type','button')
            })
        })
    </script>

{% endblock %}

todo_project/articles/templates/articles/articles_detail.html
{% extends 'base_layout.html' %}
{% block title %}
    {{ article.title }} Details
{% endblock%}
{% block content %}
    <div class="col-sm-8 offset-sm-2 my-marg-top">
        <img class="img-thumbs img-fluid rounded mx-auto d-block" src="{{ article.thumbnail.url }}" alt="">
        <hr>
        <p class="h3 mod-color">{{ article.title.capitalize }}</p>
        <p class="text-justify mod-para">{{ article.body }}</p>
        <br><br>
        <p class="mod-author">Author: {{ article.author }}</p>
        <br>
        <p class='mod-date text-right'>{{ article.date }}</p>
        <br>
        <div class="row">
            <div class="col-sm-3 offset-sm-9">
                <a href="{%url 'articles:list'%}" class="btn btn-block btn-success">Back</a>
            </div>
        </div>
    </div>
    <style>
        .img-thumbs{
            max-width:200px;
        }

        .mod-para{
            color:white;
        }
        .mod-date{
            color:rgb(189, 186, 186)
        }
        .my-marg-top{
            margin-top:80px;
        }
        .mod-color{
            color:rgb(236, 225, 118);
        }
        .mod-author{
            color:rgb(236, 225, 118);
        }
    </style>
{% endblock %}

todo_project/articles/templates/articles/articles_detail_owner.html
{% extends 'base_layout.html' %}
{% block title %}
    {{ article.title }} Details
{% endblock%}
{% block content %}
    <div class="col-sm-8 offset-sm-2 my-marg-top">
        <img class="img-thumbs img-fluid rounded mx-auto d-block" src="{{ article.thumbnail.url }}" alt="">
        <hr>
        <p class="h3 mod-color">{{ article.title.capitalize }}</p>
        <p class="text-justify mod-para">{{ article.body }}</p>
        <br><br>
        <p class="mod-author">Author: {{ article.author }}</p>
        <br>
        <p class='mod-date text-right'>{{ article.date }}</p>
        <br>
        <hr>
        <div class="row">
            <div class="col-sm-4">
                <a href="{%url 'articles:create' article.id %}" class="btn btn-block btn-primary">Edit</a>
            </div>
            <div class="col-sm-4">
                <form action="/articles/delete/{{ article.id }}/" method='POST'>
                    {% csrf_token %}
                    <button type="submit" class='btn btn-danger btn-block'>Delete</button>
                </form>
            </div>
            <div class="col-sm-4">
                <a href="{%url 'articles:owned'%}" class="btn btn-block btn-success">Back</a>
            </div>
        </div>
    </div>
    <style>
        .img-thumbs{
            max-width:200px;
        }

        .mod-para{
            color:white;
        }

        .mod-date{
            color:rgb(189, 186, 186)
        }

        .my-marg-top{
            margin-top:80px;
        }

        .mod-color{
            color:rgb(236, 225, 118);
        }

        .mod-author{
            color:rgb(236, 225, 118);
        }

        .col-sm-4{
            margin-bottom:5px !important;
        }

        .btn-primary{
            background-color:rgba(0, 110, 184, 0.411);
            border:none !important;
        }

        .btn-success{
            background-color:rgba(86, 207, 116, 0.425);
            border:none !important;
        }

        .btn-danger{
            background-color:rgba(212, 73, 73, 0.479);
            border:none;
        }
    </style>
{% endblock %}

todo_project/articles/templates/articles/articles_index.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %}
    Home - ( {{ user }} )
{% endblock%}
{% block content %}
    {% if count == 0 %}
        <div class="col-sm-6 offset-sm-3 my-img-container">
            <img class="notFound img-fluid rounded mx-auto d-block" src="{% static 'notfound.png'%}" alt="">
        </div>    
    {% endif %}
    <div class="col-sm-12 my-box ">
        <div class="row">
            <div class="col-sm-5 offset-sm-5">
                <input type="text" id="myInput" class="form-control btn-block search-input" placeholder='Search Here...'>
            </div>
        </div>

        
        {% for article in articles %}
            <div id="myTable">
                <div id="myData" class="col-sm-8 offset-sm-2 modified-con-articles">
                    <h3 class="mod-h3"><a href="{% url 'articles:detail' article.pk %}">{{ article.title.capitalize }}</a></h3>
                    <p class="mod-author">Author: {{ article.capital }}</p>
                    <hr class="lead">
                    <p class="snippets">{{ article.snippets }}<span class='seemore'><a href="{% url 'articles:detail' article.pk %}">see more</a></span></p>
                    <p class="text-right mod-date">{{ article.date }}</p>
                </div>
            </div>
        {% endfor %}
        
    </div>

    <script>
        $(document).ready(function(){
          $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable #myData").filter(function() {
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
          });
        });
    </script>

    <style>
        .my-img-container{
            margin-top:70px;
        }

        .snippets{
            color:white;
        }

        .my-box{
            margin-top:50px;
        }

        .mod-h3 a, .mod-h3{
            color:white;
            padding-top:10px !important;
        }

        .mod-date{
            color:rgb(175, 177, 175);
            font-size:13px;
        }

        .modified-con-articles{
            background-color:rgba(31, 30, 30, 0.664);
            border:1px solid rgba(31, 30, 30, 0.664);
            border-radius:7px;
            min-height:150px;
            max-height:300px;
            margin-bottom:20px;
            margin-top:10px;
        }

        .seemore a{
            color:rgb(151, 148, 148) !important;
        }

        .mod-author{
            color:rgb(231, 230, 154);
            font-size:15px;
        }

        .search-input{
            background-color:rgba(19, 18, 18, 0.521);
            border:1px solid rgba(204, 199, 199, 0.507);
            color:white;
            margin-top:20px;
        }       
    </style>
{% endblock %}

todo_project/articles/templates/articles/articles_my_article.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %}
    My Articles - ( {{ user }} )
{% endblock%}
{% block content %}
    {% if count == 0 %}
        <div class="col-sm-6 offset-sm-3 my-img-container">
            <img class="notFound img-fluid rounded mx-auto d-block" src="{% static 'notfound.png'%}" alt="">
        </div>    
    {% endif %}
    <div class="col-sm-12 my-box">
        <div class="row">
        {% for article in articles %}
            <div class="col-sm-8 offset-sm-2 modified-con-articles">
                <h3 class="mod-h3"><a href="{% url 'articles:detailowned' article.pk %}">{{ article.title.capitalize }}</a></h3>
                <p class="mod-author">Author: {{ article.capital }}</p>
                <hr class="lead">
                <p class="snippets">{{ article.snippets }}<span class='seemore'><a href="{% url 'articles:detailowned' article.pk %}">see more</a></span></p>
                <p class="text-right mod-date">{{ article.date }}</p>
            </div>
        {% endfor %}
        </div>
    </div>

    <style>

        .snippets{
            color:white;
        }

        .my-box{
            margin-top:50px;
        }

        .mod-h3 a, .mod-h3{
            color:white;
            padding-top:10px !important;
        }

        .mod-date{
            color:rgb(175, 177, 175);
            font-size:13px;
        }

        .modified-con-articles{
            background-color:rgba(31, 30, 30, 0.664);
            border:1px solid rgba(31, 30, 30, 0.664);
            border-radius:7px;
            min-height:150px;
            max-height:300px;
            margin-bottom:20px;
        }

        .my-box{
            margin-top:80px;
        }

        .seemore a{
            color:rgb(151, 148, 148) !important;
        }

        .mod-author{
            color:rgb(231, 230, 154);
            font-size:15px;
        }

        .my-img-container{
            margin-top:70px;
        }

            
    </style>
{% endblock %}

todo_project/templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{%static 'jm.png' %}" rel="icon">
    <title>
        {% block title%}

        {% endblock %}
    </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'articles:list'%}">My Todo App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link  {% if active1 == 'active'%}{{ active1 }}{% endif %}" href="{% url 'articles:create' %}">Create Article</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active2 == 'active'%}{{ active2 }}{% endif %}" href="{% url 'articles:list' %}">Public Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active3 == 'active'%}{{ active3 }}{% endif %}" href="{% url 'articles:owned' %}">My Articles</a>
            </li>
            <li class="nav-item">
                <form action="{%url 'accounts:logout'%}" method='POST'>
                    {% csrf_token %}
                    <button class="nav-link btnLogout">Logout</button><br>
                </form>
            </li>
            {% else %}
                <a class="nav-link  {% if active4 == 'active'%}{{ active4 }}{% endif %}" href="{% url 'accounts:login' %}">Login</a><br>
                <a class="nav-link  {% if active5 == 'active'%}{{ active5 }}{% endif %}" href="{% url 'accounts:signup' %}">Register</a><br>
            {% endif %}
          </ul>
        </div>
      </nav>
      

      <style>

          body{
              background-image:url('{%static "bg.jpg"%}');
              background-repeat: no-repeat;
            background-attachment: fixed;
          }
          .btnLogout{
              border:none;
              background-color:rgba(43, 43, 43, 0.001);
              color:red;
              float:left;
          }
      </style>














        
        
    
        
    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>